name: Bug report
description: Report errors or unexpected behavior
labels: [bug]
body:
  - type: checkboxes
    attributes:
      label: Do you have the latest versions of Spicetify, Spotify and ShadeX?
      description: It is difficult to support all versions of Spicetify/Spotify, so we only provide support for the latest versions. And don't forget to update the theme itself if you've installed it locally, your issue may already have been fixed.
      options:
        - label: I'm using the latest versions of Spicetify, Spotify and ShadeX
          required: true
  - type: checkboxes
    attributes:
      label: Is there already an issue for your problem?
      description: Please make sure you are not creating an already submitted <a href="https://github.com/sanoojes/Spicetify-ShadeX/issues">issue</a>. Check closed issues as well.
      options:
        - label: I have checked older issues, open and closed
          required: true
  - type: checkboxes
    attributes:
      label: Is your problem definitely caused by the theme?
      description: Please make sure the theme is the source of the problem and not another extension/custom app or the Spotify app itself.
      options:
        - label: I have checked the app behavior without the theme and it is different
          required: true
  - type: textarea
    attributes:
      label: Environment & Computer Info
      description: |
        Please provide the details of the system ShadeX is running on:
          - Copy the information from the "About" window (`⋯` button -> Help -> About -> expand -> click the Copy to Clipboard button)
          - Write where you got the Spotify app

        Please also tell us how you installed the theme.
      value: |
        - Spotify version:
        - Installed from: (Windows Store, Spotify site, Flatpak, etc)
        - Spicetify version:
        - Color scheme:
        - Extensions:
        - Custom apps:
        - ShadeX installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
      placeholder: |
        - Spotify version: for Windows 1.2.11.916.geb595a67
        - Installed from: Spotify site
        - Spicetify version: v2.18.1
        - Color scheme: darkmono
        - Extensions: fullAlbumDate.js, adblock.js
        - Custom apps: marketplace, lyrics-plus
        - ShadeX installation method: Spicetify Marketplace
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        List steps to reproduce the error and details on what happens and what you expected to happen.
      placeholder: |
        1. Please number your steps like so.
        2. This helps readability of your instructions.

        Feel free to write down additional notes you may want us to know.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots
      description: Place any screenshots of the issue here if needed
    validations:
      required: false
